config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :groups do
    member do
      post 'add-group_users'
      get 'new-users'
      delete 'delete-group-users'
      get 'show-group-users'
    end
  end

  root to: 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User', optional: false
  has_many :tasks, class_name: 'Task', dependent: :destroy
  has_and_belongs_to_many :users

  validates :owner, :name, presence: true
  validates :single_user, inclusion: { in: [true, false] }
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :reporter, class_name: 'User', optional: false
  belongs_to :assignee, class_name: 'User', optional: true
  belongs_to :group, optional: false

  before_update :ensure_immutable_associations

  scope :from_group, ->(group) { where(group:) }

  private

  def ensure_immutable_associations
    if reporter_id_changed?
      errors.add(:reporter_id, "can't be changed")
      throw(:abort)
    end

    return unless group_id_changed?

    errors.add(:group_id, "can't be changed")
    throw(:abort)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :owned_groups, class_name: 'Group', foreign_key: 'owner_id', dependent: :destroy
  has_many :reported_tasks, class_name: 'Task', foreign_key: 'reporter_id', dependent: :nullify
  has_many :assigned_tasks, class_name: 'Task', foreign_key: 'assignee_id', dependent: :nullify
  has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authorize_user, only: %i[show show_group_users]
  before_action :authorize_owner, only: %i[edit update destroy add_group_users delete_group_user]

  def index
    @groups = current_user.groups
  end

  def show; end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id

    @group.users << User.where(id: current_user.id)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy!

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def new_users;end


  def add_users
    user_ids = params[:user_ids]

    @group.users << User.where(id: user_ids)

    respond_to do |format|
      format.html { redirect_to group_url(@group), notice: 'Users were successfully added to the group.' }
      format.json { head :no_content }
    end
  end

  def show_users;end

  def delete_user
    user_id = params[:user_id]

    @group.users.delete(User.find(user_id))

    respond_to do |format|
      format.html { redirect_to group_url(@group), notice: 'User was successfully removed from the group.' }
      format.json { head :no_content }
    end
  end

  private

  def authorize_owner
    return if @group.owner_id == current_user.id

    render json: { error: 'Not an Owner' }, status: :unauthorized
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :single_user)
  end

  def authorize_user
    return if @group.users.include?(current_user)

    render json: { error: 'Not Authorized' }, status: :unauthorized
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.assigned_tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.reporter_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :status, :due_date, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/groups/_add_group_users_form.html.haml
= form_tag add, method: :post do
  - User.all.each do |user|
    .user-checkbox
      = check_box_tag 'user_ids[]', user.id
      = label_tag "user_ids_#{user.id}", user.email

  = submit_tag "Add Selected Users"

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
            
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :single_user
    = f.check_box :single_user
  .actions
    = f.submit 'Save'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

%table
  %thead
    %tr
      %th Owner
      %th Name
      %th Single user
      %th
      %th
      %th

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.owner.email
        %td= group.name
        %td= group.single_user
        %td= link_to 'Show', group
        %td= link_to 'Edit', edit_group_path(group)
        %td= button_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Group', new_group_path
%br
= link_to 'Back', root_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/new_users.html.haml
%h1 Add Users

=render 'add_group_users_form'
%br
= link_to 'Back', groups_path

app/views/groups/show.html.haml
%h1 = @group.name
%p
  %b Owner:
  = @group.owner.email
%p
  %b Single user:
  = @group.single_user

%br
- if current_user == @group.owner
  = link_to 'Edit', edit_group_path(@group)
  \|
  = button_to 'Destroy', @group, method: :delete, data: { confirm: 'Are you sure?' }
  - if !@group.single_user
    \|
    = link_to 'Show Users', show_group_users_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/groups/show_users.html.haml
%h1= @group.name + ': Users'

- if current_user == @group.owner
  = link_to 'Add Users', add_group_users_group_path(@group)

%tbody
  - @group_users.each do |user|
    %tr
      %td= user.email
      - if current_user == @group.owner
        %td= button_to 'Remove user', delete_group_user_path(@group, user), method: :delete, data: { confirm: 'Are you sure?' }

app/views/home/index.html.haml
%h1 Home#index
- if user_signed_in?
  = link_to "Groups", groups_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TaskManagementApp
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    - if user_signed_in?
      = link_to "Profile", edit_user_registration_path
      %br
      = button_to "Logout", destroy_user_session_path, method: :delete
    - else
      = link_to "Sign Up", new_user_registration_path
      %br
      = link_to "Sign In", new_user_session_path
    = yield
    %p.notice= notice
    %p.alert= alert

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :due_date
    = f.datetime_field :due_date
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th Name
      %th Status
      %th User
      %th Due date
      %th Description
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.status
        %td= task.user
        %td= task.due_date
        %td= task.description
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Status:
  = @task.status
%p
  %b User:
  = @task.user
%p
  %b Due date:
  = @task.due_date
%p
  %b Description:
  = @task.description

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path